name: ww-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - dash
  - plotly
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - dash-bootstrap-components
  - diskcache
  - pymannkendall
  - gunicorn
