name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger builds on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: poeli/wastewater_qpcr_app:latest
          file: Dockerfile  # Update this if your Dockerfile has a different name or location
